import{clamp,labels,systemLabels,giantWords}from'./config.js';import{initViewers,applyScene}from'./viewers.js';
const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
const exp=$('[data-experience]'),pre=$('[data-preloader]'),bar=$('[data-load-bar]'),val=$('[data-load-value]'),markers=$$('[data-marker]'),chapters=$$('[data-chapter]'),fx=$$('[data-fx]'),nav=$$('[data-jump]'),prog=$('[data-progress]'),cur=$('[data-current]'),label=$('[data-scene-label]'),system=$('[data-system-label]'),ga=$('[data-giant-a]'),gb=$('[data-giant-b]'),assembly=$('[data-assembly-state]'),form=$('[data-mail-form]');
let active=0,fake=0,done=false;const timer=setInterval(()=>{fake=Math.min(fake+Math.ceil(Math.random()*7),90);bar.style.width=fake+'%';val.textContent=fake+'%'},120);
function finish(){if(done)return;done=true;clearInterval(timer);bar.style.width='100%';val.textContent='100%';setTimeout(()=>pre.classList.add('done'),320)}
function scene(i){i=clamp(i,0,chapters.length-1);active=i;chapters.forEach((e,n)=>e.classList.toggle('is-active',n===i));fx.forEach((e,n)=>e.classList.toggle('is-active',n===i));nav.forEach(e=>e.classList.toggle('is-active',Number(e.dataset.jump)===i));cur.textContent=String(i+1).padStart(2,'0');label.textContent=labels[i];system.textContent=systemLabels[i];ga.textContent=giantWords[i][0];gb.textContent=giantWords[i][1];prog.style.width=i/(chapters.length-1)*100+'%';exp.dataset.engine=String(i===3||i===4);applyScene(i)}
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting&&e.intersectionRatio>=.55)scene(Number(e.target.dataset.marker))}),{threshold:[.55,.75]});markers.forEach(m=>observer.observe(m));
let tick=false;addEventListener('scroll',()=>{if(tick)return;tick=true;requestAnimationFrame(()=>{const m=markers[active],local=clamp((scrollY-m.offsetTop)/Math.max(m.offsetHeight,1)+.5,0,1);document.documentElement.style.setProperty('--local',local.toFixed(4));tick=false})},{passive:true});
nav.forEach(e=>e.addEventListener('click',x=>{x.preventDefault();markers[Number(e.dataset.jump)]?.scrollIntoView({behavior:'smooth'})}));
form?.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget),subject='Fahrzeuganfrage über BROO BMW Assembly Experience',body=`Hallo BROO Performance,\n\nich interessiere mich für eine Fahrzeugoptimierung.\n\nMarke / Modell: ${d.get('vehicle')}\nBaujahr / Motor: ${d.get('engine')}\nSerienleistung: ${d.get('power')||'-'}\n\nBitte senden Sie mir eine erste Einschätzung.\n`;location.href=`mailto:info@broo-performance.de?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`});
scene(0);Promise.race([initViewers(t=>assembly.textContent=t),new Promise(r=>setTimeout(r,8000))]).finally(finish);
