import{carUid,engineUid,cameraKeys}from'./config.js';
let carApi,engineApi,carCamera,engineCamera,parts=[],currentScene=0;
const classify=n=>{n=(n||'').toLowerCase();if(/hood|bonnet|capot/.test(n))return'hood';if(/door|porte/.test(n))return'door';if(/trunk|boot|tailgate|coffre/.test(n))return'trunk';if(/wheel|rim|tire|tyre/.test(n))return'wheel';if(/glass|window|windshield/.test(n))return'glass';if(/engine|motor|turbo|intercooler|radiator|exhaust|intake/.test(n))return'engine';if(/body|chassis|shell|exterior|carbody/.test(n))return'shell';return null};
const camFrom=(base,key)=>{const t=base.target,dx=base.position[0]-t[0],dy=base.position[1]-t[1],dz=base.position[2]-t[2],r=Math.max(.1,Math.hypot(dx,dz))*key.radius,yaw=Math.atan2(dz,dx)+key.yaw;return{p:[t[0]+Math.cos(yaw)*r,t[1]+dy*key.pitch,t[2]+Math.sin(yaw)*r],t:t.slice(),f:key.fov}};
function capture(state){carApi.getNodeMap((e,nodes)=>{if(e||!nodes){state('ASSEMBLY MAP // CAMERA FALLBACK');return}const lim={hood:3,door:8,trunk:3,wheel:10,glass:6,engine:12,shell:4},count={};const list=nodes.filter(n=>{const g=classify(n.name);if(!g||n.type!=='MatrixTransform')return false;count[g]=(count[g]||0)+1;if(count[g]>lim[g])return false;n.g=g;return true});let pending=list.length;if(!pending){state('ASSEMBLY MAP // CAMERA FALLBACK');return}list.forEach(n=>carApi.getMatrix(n.instanceID,(err,m)=>{if(!err&&m?.length===16)parts.push({id:n.instanceID,g:n.g,m:m.slice()});if(!--pending){state(parts.length?`ASSEMBLY MAP // ${parts.length} MOVABLE NODES`:'ASSEMBLY MAP // CAMERA FALLBACK');applyScene(currentScene)}}))})}
function matrix(part,a){const m=part.m.slice(),x=m[12],y=m[13],z=m[14],r=Math.max(.001,Math.hypot(x,z)),nx=x/r,nz=z/r,w={hood:[.85,.55],door:[1.05,.18],trunk:[.8,.42],wheel:[.55,.06],glass:[.32,.24],engine:[.18,.06],shell:[.16,.18]}[part.g]||[.2,.1];m[12]=x+nx*a*w[0];m[13]=y+a*w[1];m[14]=z+nz*a*w[0];return m}
function init(frame,uid,type){return new Promise(resolve=>{if(!window.Sketchfab){resolve();return}new Sketchfab('1.12.1',frame).init(uid,{autostart:1,camera:0,autospin:0,dnt:1,scrollwheel:0,double_click:0,transparent:1,ui_controls:0,ui_infos:0,ui_help:0,ui_settings:0,ui_vr:0,ui_fullscreen:0,ui_annotations:0,ui_stop:0,ui_inspector:0,ui_watermark_link:0,success(api){api.start();api.addEventListener('viewerready',()=>{api.setUserInteraction(false);api.getCameraLookAt((e,c)=>{if(type==='car'){carApi=api;carCamera=e?null:c}else{engineApi=api;engineCamera=e?null:c}resolve()})})},error(){resolve()}})})}
export async function initViewers(state){await Promise.all([init(document.querySelector('#car-frame'),carUid,'car'),init(document.querySelector('#engine-frame'),engineUid,'engine')]);if(carApi)capture(state);else state('ASSEMBLY MAP // VIEWER FALLBACK')}
export function applyScene(scene){currentScene=scene;const amount=[0,0,.72,1.12,1.28,.24,0][scene]||0;parts.forEach(p=>carApi?.setMatrix(p.id,matrix(p,amount)));if(carApi&&carCamera){const c=camFrom(carCamera,cameraKeys[scene]);carApi.setCameraEasing('easeInOutQuad');carApi.setFov(c.f);carApi.setCameraLookAt(c.p,c.t,1.25)}if(engineApi&&engineCamera&&(scene===3||scene===4)){const key=scene===3?{yaw:-.5,pitch:.86,radius:.96,fov:34}:{yaw:.65,pitch:.82,radius:.86,fov:30},c=camFrom(engineCamera,key);engineApi.setCameraEasing('easeInOutQuad');engineApi.setFov(c.f);engineApi.setCameraLookAt(c.p,c.t,1.2)}}
